### PR TITLE
adding status notifier

### PR DESCRIPTION
**Pull request by zmhbh**
Hello, thanks for creating this lib, it's so powerful. When I use this lib, I realized the "controller.isShowing" doesn't work as expected. After some investigation, I found the controller.value would be changed multiple time for each user action. So I exposed this tooltip status. I also updated the example for your reference. Feel free to update these changes if there is better implementation. Thanks~

### CODE REVIEW

**Comment by zmhbh** [comment]
@Nolence Please take a look~

**Comment by stargazing-dino** [comment]
Hello ! Thank you for the PR

I'm curious to know more about the issue. The controller was a quick feature I implemented and I was scared it might not catch all use cases or be broken in some places. Before we get to this PR, do you mind creating an issue with the original problem and what you expect to happen? A video, call stack or a bunch of print logs would be helpful. I plan to work on this lib a lot soon in preparation for #20 so I wouldn't mind working on something like this soon

**Comment by zmhbh** [comment]
> Hello ! Thank you for the PR
> 
> I'm curious to know more about the issue. The controller was a quick feature I implemented and I was scared it might not catch all use cases or be broken in some places. Before we get to this PR, do you mind creating an issue with the original problem and what you expect to happen? A video, call stack or a bunch of print logs would be helpful. I plan to work on this lib a lot soon in preparation for #20 so I wouldn't mind working on something like this soon

Sure.

**Comment by stargazing-dino** [comment]
Thank you for this PR and work ! Closing as fixed in 0.0.10

**Pull request closed without merging**
