### PR TITLE
feat: add backdrop

### PR DESCRIPTION
**Pull request by nogueirahy**

### CODE REVIEW

**Comment by stargazing-dino** [comment]
Hey ! Thanks for the PR :) Unfortunately, this is a little more complicated. See #48 and the discussion there.

I just recently got back to this library after a long silence so I'll see what I can do about something like this. (Seems like a common request.)

The solution will likely (really can't be sure though) involve making a custom RenderObject similar to [RenderBackdropFilter](https://github.com/flutter/flutter/blob/cd41fdd495f6944ecd3506c21e94c6567b073278/packages/flutter/lib/src/rendering/proxy_box.dart#L1128) but that creates a `Layer` for everything in tree except the current child. Either that or the other way I'm not really a fan of which is create a stack (this works internally off layers anyways) and place the `child` above the backdrop and everything else.

**Comment by caseycrogers** [comment]
FWIW, I think an ultra simple version of this (akin to my original proposal in #48) would be very easy to add and high value:
Add a skrim behind the tooltip but in front of the child that spawned the tooltip. This is slightly substandard UX relative to a skrim that didn't cover the child, but it's WAY better IMO than the current situation where the background isn't obscured at all unless you add your own stack and own custom skrim, which is a pain.

**Comment by SungHyun22** [comment]
When will this PR be merged?

**Comment by PiotrMitkowski** [comment]
Hey @SungHyun22! As I've recently received write access from the package author, I'll try to take a look at this topic ASAP in the upcoming days and let you know about further steps.

**Comment by PiotrMitkowski** [comment]
> Hey @SungHyun22! As I've recently received write access from the package author, I'll try to take a look at this topic ASAP in the upcoming days and let you know about further steps.

@SungHyun22 slightly better approach has been proposed in https://github.com/Nolence/just_the_tooltip/pull/48. That PR has been already merged, so this one will be closed.

@nogueirahy thanks again for your work, I feel really sorry for abandoning it now. I'll do my best to avoid similar confusion in the future.

**Pull request closed without merging**
